stages:
  - documentation
  - lint
  - test
  - package
  - release

include:
  - project: 'gitlab-org/security-products/ci-templates'
    ref: 'master'
    file: '/includes-dev/upsert-git-tag.yml'
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - local: /.gitlab/ci_templates/docker.yml

default:
  image: alpine:3.18

check_docs_markdown:
  stage: documentation
  image: registry.gitlab.com/gitlab-org/gitlab-docs/lint-markdown:alpine-3.16-vale-2.20.1-markdownlint-0.32.2
  script:
    # Lint prose
    - vale --minAlertLevel error docs README.md CONTRIBUTING.md CHANGELOG.md
    # Lint Markdown
    - markdownlint --config .markdownlint.yml 'docs/**/*.md' *.md

test:
  script:
    - apk add make git neovim
    - make test
  stage: test

lint:
  script:
    - apk add make luacheck stylua
    - make lint
  stage: lint

upsert git tag:
  # Limit job execution to authorized users.
  environment:
    name: production
    url: https://gitlab.com/gitlab-org/editor-extensions/gitlab.vim/-/releases/$CI_COMMIT_REF_SLUG
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: release
