stages:
  - lint
  - test
  - release

include:
  - project: 'gitlab-org/security-products/ci-templates'
    ref: 'master'
    file: '/includes-dev/upsert-git-tag.yml'
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/License-Scanning.gitlab-ci.yml

default:
  image: alpine:3.18

test:
  script:
    - apk add make git neovim
    - make test
  stage: test

lint:
  script:
    - apk add make luacheck stylua
    - make lint
  stage: lint

upsert git tag:
  # Limit job execution to authorized users.
  environment:
    name: production
    url: https://gitlab.com/gitlab-org/editor-extensions/gitlab.vim/-/releases/$CI_COMMIT_REF_SLUG
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: release
