stages:
  - test

default:
  image: alpine:3.18

test:
  script:
  - apk add make git neovim
  - git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
  - make test

lint:
  script:
  - apk add make luacheck stylua
  - make lint
